apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-app-deployment
  namespace: 
  labels:
    app: ref-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ref-app
  template:
    metadata:
      labels:
        app: ref-app
    spec:
      containers:
      - name: ref-app
        image: simonnla/ref-app:1.1
        ports:
          - containerPort: 9000
          - containerPort: 9001
